import Head from "next/head";
import { ethers } from "ethers";
import { useEffect, useState } from "react";
import axios from "axios";
import Web3modal from "web3modal";
import { nftAddress, nftmarketAddress } from "../config";

import NFT from "../artifacts/contracts/NFT.sol/NFT.json";
import MARKET from "../artifacts/contracts/NFTMarket.sol/NFTMarket.json";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      HOME
    </div>
  );
}
