import Head from "next/head";
import { ethers } from "ethers";
import { useEffect, useState } from "react";
import axios from "axios";
import Web3modal from "web3modal";
import { nftmarketAddress } from "../config";

import MARKET from "../artifacts/contracts/NFTMarket.sol/NFTMarketplace.json";
export default function Home() {
  const [nft, setNft] = useState([]);
  const [loadingState, setLoadingState] = useState("not-loaded");

  const loadNFTs = async () => {
    // in read operation,we dont need to know anything about provider,so use JsonRpcProvider
    const provider = new ethers.providers.JsonRpcProvider(
      "https://rpc-mumbai.maticvigil.com"
    );
    const marketContract = new ethers.Contract(
      nftmarketAddress,
      MARKET.abi,
      provider
    );

    const data = await marketContract.fetchMarketItems();
    const items = await Promise.all(
      data.map(async (i) => {
        const tokenUri = await marketContract.tokenURI(i.tokenId);
        const meta = await axios.get(tokenUri);
        let price = ethers.utils.formatUnits(i.price.toString(), "ether");
        let item = {
          price,
          tokenId: i.tokenId.toNumber(),
          seller: i.seller,
          owner: i.owner,
          image: meta.data.image,
          name: meta.data.name,
          description: meta.data.description,
        };
        return item;
      })
    );
    setNft(items);
    setLoadingState("loaded");
  };

  const buyNft = async (nft) => {
    const web3modal = new Web3modal();
    const connection = await web3modal.connect();
    const provider = new ethers.providers.Web3Provider(connection);
    const signer = provider.getSigner();
    const contract = new ethers.Contract(nftmarketAddress, MARKET.abi, signer);
    const price = ethers.utils.parseUnits(nft.price.toString(), "ether");
    const transaction = await contract.createMarketSale(
      nftAddress,
      nft.tokenId,
      { value: price }
    );
    await transaction.wait();
    // after finishing
    loadNFTs();
  };
  useEffect(() => {
    loadNFTs();
  }, []);

  if (loadingState === "loaded" && !nft.length)
    return <h1 className="px-20 py-10 text-3xl">No items in marketplace</h1>;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center">
        <div className="px-4" style={{ maxWidth: "1600px" }}>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 pt-4">
            {nft.map((oneNft, index) => (
              <div
                key={index}
                className="border shadow rounded-xl overflow-hidden"
              >
                <img src={oneNft.image} />
                <div className="p-4">
                  <p
                    style={{ height: "64px" }}
                    className="text-2xl font-semibold"
                  >
                    {oneNft.name}
                  </p>
                  <div style={{ height: "70px", overflow: "hidden" }}>
                    <p className="text-gray-400">{oneNft.description}</p>
                  </div>
                </div>
                <div className="p-4 bg-black">
                  <p className="text-2xl font-bold text-white">
                    {oneNft.price} Matic
                  </p>
                  <button
                    className="mt-4 w-full bg-pink-500 text-white font-bold py-2 px-12 rounded"
                    onClick={() => buyNft(oneNft)}
                  >
                    Buy
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
